###
# 数据库用户（正确）
POST http://127.0.0.1:7573/auth/api/login
Content-Type: application/json

{
  "username": "user_1",
  "password": "123",
  "authType": "database"
}

###{
###  "username": "editor_1",
###  "password": "123",
###  "authType": "database"
###}
###
###{
###  "username": "adm_1",
###  "password": "123",
###  "authType": "database"
###}
###

# LDAP 用户登录（正确）
POST http://127.0.0.1:7573/auth/api/login
Content-Type: application/json

{
  "username": "ldap_adm_1",
  "password": "123",
  "authType": "ldap"
}

###{
###  "username": "ldap_editor_1",
###  "password": "123",
###  "authType": "ldap"
###}
###
###{
###  "username": "ldap_user_1",
###  "password": "123",
###  "authType": "ldap"
###}
###

###

# github 用户
POST http://127.0.0.1:7573/auth/api/login
Content-Type: application/json

{
  "code": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
  "state": "xxxxxxxx",
  "authType": "github"
}

###


###

# 确保 cloud-auth 微服务确实监听了 /oauth2/authorization/github 路径。 直接访问后端（绕过网关） 如果能返回 302 Found 并跳转到 GitHub，则说明后端正常。
GET http://localhost:9001/oauth2/authorization/github

###
## 观察是否能成功转发到后端 如果能返回 302 Found 并跳转到 GitHub，则说明后端正常。

GET http://localhost:7573/oauth2/authorization/github

