spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.135:3306/auth_db?useSSL=false&serverTimezone=UTC
    username: auth_user
    password: Adm!nP@ss2024
  application:
    name: cloud-auth
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.0.135:8848}
        namespace: ${NACOS_NAMESPACE:df35fbb2-86a5-492c-bd80-cf2e8a51e53b}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:YourSecurePassword123}
      config:
        server-addr: ${NACOS_SERVER_ADDR:192.168.0.135:8848}
        namespace: ${NACOS_NAMESPACE:df35fbb2-86a5-492c-bd80-cf2e8a51e53b}
        group: DEFAULT_GROUP
        file-extension: yaml
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:YourSecurePassword123}
        refresh-enabled: true
        # 添加共享配置
        shared-configs:
          - data-id: dubbo-common.yaml
            group: DEFAULT_GROUP
            refresh: true
  security:
    csrf:
      enabled: false
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li74AbOLBmiOMlzn
            client-secret: eafdac391321856dd77d209cb1eb56c140e8a74b
            scope: read:user
            redirect-uri: "http://localhost:8081/login/oauth2/code/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  jackson:
    deserialization:
      fail-on-unknown-properties: false

  ldap:
    urls: ldap://cloud-ldap:389
    base: ou=people,dc=example,dc=com
    # 管理员DN（如有）
    username: cn=admin,dc=example,dc=com
    # 管理员密码
    password: Adm!nP@ss2024
    # 用户搜索模式
    userDnPattern: cn={0},ou=people
    password-attribute: userPassword
    # 根据实际加密方式调整
    password-encoder: md5
jwt:
  secretKey: dJy5MH1u73qIRu74OuqKHTALBUGqVfyAoFLiCUnwl4Y=
  expiration: 86400000 # 24小时
server:
  port: 9001
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.cloud.auth: DEBUG
    org.springframework.ldap: DEBUG
    org.springframework.cloud.gateway: TRACE   # 网关请求调试
    reactor.netty: DEBUG                       # Netty 请求详情
    org.springframework.cloud.loadbalancer.core: TRACE
    org.springframework.security.access: DEBUG
dubbo:
  protocol:
    port: 20880  # 为不同服务指定不同端口
