spring:
  application:
    name: rabbitmq-demo
  #RabbitMq配置
  rabbitmq:
    host: 192.168.0.13
    port: 5672
    username: youyu-dev
    password: youyu-dev
    virtual-host: /youyu-cloud-dev
    # 连接池配置
    cache:
      connection:
        mode: channel
      channel:
        size: 25
        checkout-timeout: 10000
    # 开启发送端消息抵达Queue确认
    publisher-returns: true
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    template:
      # 只要消息抵达Queue，就会异步发送优先回调returnfirm
      mandatory: true
    listener:
      simple:
        # 每次从RabbitMQ获取的消息数量
        prefetch: 1
        default-requeue-rejected: false
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 10
        # 签收模式为手动签收-那么需要在代码中手动ACK
        acknowledge-mode: manual
        # 重试机制
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 5
          multiplier: 2.0