eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://interview-eureka:8761/eureka

spring:
  application:
    name: interview-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ylanhds/config-repo # 配置仓库地址
          default-label: main # 分支名称
server:
  port: 8888
